//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aha.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aha.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string Q1ChooseLanguagePicker {
            get {
                return ResourceManager.GetString("Q1ChooseLanguagePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Age.
        /// </summary>
        internal static string Q2EnterYourAge1 {
            get {
                return ResourceManager.GetString("Q2EnterYourAge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your age.
        /// </summary>
        internal static string Q2EnterYourAge2 {
            get {
                return ResourceManager.GetString("Q2EnterYourAge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        internal static string Q3Art {
            get {
                return ResourceManager.GetString("Q3Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        internal static string Q3Automation {
            get {
                return ResourceManager.GetString("Q3Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering.
        /// </summary>
        internal static string Q3Engineering {
            get {
                return ResourceManager.GetString("Q3Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography.
        /// </summary>
        internal static string Q3Geography {
            get {
                return ResourceManager.GetString("Q3Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Q3History {
            get {
                return ResourceManager.GetString("Q3History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Q3Music {
            get {
                return ResourceManager.GetString("Q3Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceans.
        /// </summary>
        internal static string Q3Oceans {
            get {
                return ResourceManager.GetString("Q3Oceans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science.
        /// </summary>
        internal static string Q3Science {
            get {
                return ResourceManager.GetString("Q3Science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Interest.
        /// </summary>
        internal static string Q3SelectInterests1 {
            get {
                return ResourceManager.GetString("Q3SelectInterests1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the box next to the subjects that interest you..
        /// </summary>
        internal static string Q3SelectInterests2 {
            get {
                return ResourceManager.GetString("Q3SelectInterests2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        internal static string Q3Technology {
            get {
                return ResourceManager.GetString("Q3Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string QFinish {
            get {
                return ResourceManager.GetString("QFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting!.
        /// </summary>
        internal static string QInitalGreeting1 {
            get {
                return ResourceManager.GetString("QInitalGreeting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Discovery World&apos;s immersive experience with A.I.!.
        /// </summary>
        internal static string QInitialGreeting2 {
            get {
                return ResourceManager.GetString("QInitialGreeting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Get Started!.
        /// </summary>
        internal static string QInitialGreeting3 {
            get {
                return ResourceManager.GetString("QInitialGreeting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Survey.
        /// </summary>
        internal static string QInitialStartButton {
            get {
                return ResourceManager.GetString("QInitialStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string QNextButton {
            get {
                return ResourceManager.GetString("QNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a Message.
        /// </summary>
        internal static string Type_a_Message {
            get {
                return ResourceManager.GetString("Type a Message", resourceCulture);
            }
        }
    }
}
